### ISSUE TITLE
JS == (equality with type coercion) 

### ISSUE THREAD

**Issue by gkz** [gkz/coffee2ls#13]
js2coffee translates this to `is` - most of the time this is fine, but in some cases the code was relying on type coercion and will break

**Comment by vendethiel** [comment]
This is actually a very tricky one. What can one do to guess what was it meant to use ?

**Comment by gkz** [comment]
Yes, indeed. I've spent hours hunting down bugs due to people relying on the type coercion. :(
LiveScript has `~=` and `!~=`, but I don't want to translate every single equality to that instead of `is` because of a few cases - but in the end there might not be much choice. Also, this would require us forking js2coffee.
