### ISSUE TITLE
variable shadowing

### ISSUE THREAD

**Issue by gkz** [gkz/coffee2ls#14]
js2coffee does not deal with variable shadowing at all which is terrible

input JS:

```
var i = 0;
(function() {
    var i = 1
}());
```

resulting CoffeeScript:

```
i = 0
(->
  i = 1
)()
```

which of course gets translated into the following LiveScript be coffee2ls:

```
i = 0

(-> i := 1)!
```

which is completely incorrect and breaks things

**Comment by vendethiel** [comment]
Again, do you have any idea ? That's (sadly) the very nature of coffee

**Comment by gkz** [comment]
we need to have our own fork of js2coffee to fix this problem
