### ISSUE TITLE
var def not hoisted 

### ISSUE THREAD

**Issue by gkz** [gkz/coffee2ls#8]
failing:

```
->
  x = 10
x = 2
```

compiles to

```
-> x = 10

x = 2
```

expected:

```
-> x := 10

x = 2
```

**Comment by Whoaa512** [comment]
Any ideas about which file I might start in to fix this?

**Comment by gkz** [comment]
coffee2ls is way out of date with redux

but if you need to hack it in, you'll have to modify [coffee2ls-codegen](https://github.com/gkz/coffee2ls-codegen) - look into the AssignOp section
